services:
  backend:
    build: ./backend
    environment:
      # Supabase connection (provided)
      DATABASE_URL: "postgresql://postgres.rtoedavwkyicvokbcxkr:OIJlRB7WHB2AMg@aws-1-eu-central-1.pooler.supabase.com:5432/postgres?pool_mode=session"
      DB_SSL: "true"
      PGUSER: "postgres.rtoedavwkyicvokbcxkr"
      PGPASSWORD: "OIJlRB7WHB2AMg"
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
